### ISSUE TITLE
[feat] : 초기 & Asset 세팅

### ISSUE THREAD

**Issue by zzzl-523** [skatch-devocean-young/frontend#1]
### 📝 Description
- 프로젝트 생성
- 내비게이션, 페이지, 컴포넌트, 폰트, 이미지 등 세팅

---
### 📝 Todo
- [x] 프로젝트 생성
- [x]  내비게이션 세팅
- [x]  폴더 구조 세팅
- [x]  예시 컴포넌트 생성
- [x]  asset (폰트, 이미지) 세팅
