### ISSUE TITLE
[feat] : 주최자 - 행사관리 - 행사생성페이지

### ISSUE THREAD

**Issue by zzzl-523** [skatch-devocean-young/frontend#11]
### 📝 Description

- 행사 생성/수정 페이지
- create/modify를 container 구분해서 생성
- 사진, 날짜 금액 등 정보 입력받기

---

### 📝 Todo

- [ ] 포스터 사진 입력받기 : 카메라&앨범 연동
- [ ] 공연 이름 : string
- [ ] 공연 날짜 입력받기 : 달력
- [ ] 장소 : string
- [ ] 인원 : 숫자
- [ ] 금액 : 숫자
- [ ] 예매날짜(시작~기한) : 달력
- [ ] 주최자 한마디 : string
- [ ] 입금기한 : 달력
- [ ] 입금기한 -> 금액 0이면 보이지 않게 && Null 로 전송
