### ISSUE TITLE
[feat] 주최자 - 행사관리

### ISSUE THREAD

**Issue by zzzl-523** [skatch-devocean-young/frontend#12]
### 📝 Description

- 행사관리 페이지 이중탭 구조 구현
- 탭1 : 티켓 관리, 출석 관리
- 탭2 : 승인 대기중, 승인 완료, 취소 신청, 취소 완료

---

### 📝 Todo

- [ ] 신규 페이지 생성 - 이중탭구조
- [ ] 각 탭의 페이지 생성
- [ ] 승인 대기중 -> 승인 완료
- [ ] 취소 신청 -> 취소 완료
- [ ] 미참석 -> 참석
