### ISSUE TITLE
[feat] : 행사 피드 & 상세페이지

### ISSUE THREAD

**Issue by zzzl-523** [skatch-devocean-young/frontend#2]
### 📝 Description

- 행사 컴포넌트 생성
- 행사 피드 페이지
- 행사 상세페이지

---

### 📝 Todo

- [x] 행사 컴포넌트 생성
- [x] 행사 피드 페이지 생성
- [x] 행사 상세페이지 생성
