### ISSUE TITLE
[feat] : 티켓 꾸미기UI

### ISSUE THREAD

**Issue by zzzl-523** [skatch-devocean-young/frontend#4]
### 📝 Description

- 티켓꾸미기 UI 위주로 구현

---

### 📝 Todo

- [x] 티켓꾸미기 페이지
- [x] 사진앨범 버튼 클릭 -> 사진 불러오기 -> 꾸미기 모달 띄우기
- [x] 생성형 AI 클릭 -> 효과 적용
- [x] 텍스트 버튼 클릭 -> 텍스트 입력
- [ ] 텍스트 꾸미기는 아직
