### ISSUE TITLE
[feat] : 마이페이지(공통)

### ISSUE THREAD

**Issue by zzzl-523** [skatch-devocean-young/frontend#6]
### 📝 Description

- 마이페이지 구현
- 참여자/주최자 공통 화면
- 일부 변동사항은 추후 파라미터 등으로 관리 예정 (컴포넌트는 공통으로 사용)

---

### 📝 Todo

- [x] 계정 정보 컴포넌트
- [x] 메뉴 목록
- [x] 메뉴 컴포넌트 (목록에 들어갈 것 / 푸시알림 버튼 다르게)
- [x] 참여자/주최자 전환 버튼
