### ISSUE TITLE
[feat] : 주최자 - 마이페이지

### ISSUE THREAD

**Issue by zzzl-523** [skatch-devocean-young/frontend#8]
### 📝 Description

- 아티스트 정보 메뉴 추가
- 새로운 페이지로 구현 (Host, User 구분)
- **TODO: 추후 아티스트 정보 페이지 개발 필요**

---

### 📝 Todo

- [x] HostMyPageScreen 신규 생성
- [x] "아티스트 정보" 메뉴 추가
- [x] 기존 MyPageScreen -> UserMyPageScreen 으로 변경
- [ ] 아티스트 정보 screen 개발
