### ISSUE TITLE
[feat] : 유저 - 행사 홈 화면

### ISSUE THREAD

**Issue by juwonleee** [skatch-devocean-young/frontend#9]
### 📝 Description

- 유저 쪽 행사 홈 화면 UI 구현

---

### 📝 Todo

- [ ] 나의 취향에 맞는 공연 섹션 UI
- [ ] 요즘 뜨는 아티스트 섹션 UI
- [ ] 인기공연 섹션 UI
- [ ] 신청한 공연 티켓 floating 섹션 UI
